### ISSUE TITLE
Error on lastest Arch with Python 3.10 and Inkscape 1.1

### ISSUE THREAD

**Issue by horga83** [ChrisWag91/Inkscape-Lasertools-Plugin#32]
Running the plugin gives this error.  I added some text, selected Object to Path and then ran the plugin.

Traceback (most recent call last):
  File "/home/george/.config/inkscape/extensions/lasertools.py", line 1744, in <module>
    laser_gcode().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/george/.config/inkscape/extensions/lasertools.py", line 1715, in effect
    self.area_fill()
  File "/home/george/.config/inkscape/extensions/lasertools.py", line 1152, in area_fill
    np_finalLines = np.delete(np_finalLines, index_zeros, axis=0)
  File "<__array_function__ internals>", line 180, in delete
  File "/usr/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5128, in delete
    keep[obj,] = False
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by horga83** [comment]
Ok update to this.
It seems to be due to having another layer present, even though that layer is locked and hidden.
